version: '3'

services:
  db:
    image: postgres

  redis:
    image: redis

  nginx:
    build: ./nginx
    volumes:
      - ./socket:/socket
    ports:
      - "8000:80"
    depends_on:
      - api
      - websocket

  websocket:
    build: ./uvicorn
    volumes:
      - ./api:/api
      - ./socket:/socket
    depends_on:
      - redis
      - db

  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./socket:/socket
    depends_on:
      - db
      - redis

